[build]
  # Build command - builds both client and server
  command = "pnpm build"
  
  # Output directory for the built site
  functions = "netlify/functions"
  publish = "publish"

[build.environment]
  # Use pnpm as package manager
  NPM_FLAGS = "--prefer-offline --no-audit"

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
